// SPDX-License-Identifier: 0BSD
// SPDX-FileCopyrightText: 2025 kaleido
#include "lib/fax.h"
#include "misc/bit.h"
#include "misc/common.h"
#include "misc/iff.h"
#include "misc/math.h"

// Generated by fax.py
#include "fax_table.h"

const char * fax_coding_str(enum fax_coding coding) {
	switch (coding) {
	case fax_none: return "No compression";
	case fax_mh: return "Modified Huffman";
	case fax_mr: return "Modified READ";
	case fax_mmr: return "Modified Modified READ";
	}
	return "???";
}

const char * gphd_ph_str(enum gphd_ph ph) {
	switch (ph) {
	case gphd_ph_unlimited: return "Unlimited";
	case gphd_ph_a4: return "A4 PAGE 297 mm";
	case gphd_ph_b4: return "B4 PAGE 364 mm";
	}
	return "???";
}

static void fax_set_img_params(struct wuimg *img) {
	img->channels = 1;
	img->bitdepth = 8;
	img->bitrange = 1;
	img->attr = pix_inverted;
}

static uint32_t huff_get_pair(const uint32_t bits, const uint32_t nr,
const bool ink, const bool level2, const uint32_t prev_val, uint16_t *val) {
	const uint32_t idx = ((uint32_t)level2 << FAX_LEVEL1_BITS)
		| (prev_val << FAX_LEVEL2_BITS)
		| (bits >> (32 - nr));
	const uint32_t off = ink ? FAX_BLACK_OFFSET : FAX_WHITE_OFFSET;
	*val = huff_get_val(FAX_HUFFMAN_TABLE[idx + off]);
	return huff_get_bits(FAX_HUFFMAN_TABLE[idx + off]);
}

static bool set_adv(uint32_t *bits, uint32_t *adv, uint32_t nr) {
	if (nr) {
		*bits <<= nr;
		*adv += nr;
	}
	return nr;
}

static bool huffman_find(uint32_t *bits, uint32_t *adv, uint16_t *val,
const bool ink) {
	if (*bits >> (32 - 8) == 0) {
		return false;
	}
	uint32_t adv1 = huff_get_pair(*bits, FAX_LEVEL1_BITS, ink, false, 0, val);
	if (set_adv(bits, adv, adv1)) {
		return true;
	}
	*bits <<= FAX_LEVEL1_BITS;
	*adv += FAX_LEVEL1_BITS;
	return set_adv(bits, adv,
		huff_get_pair(*bits, FAX_LEVEL2_BITS, ink, true, *val, val));
}

static void finish_line(struct bitstrm *bs, uint32_t adv, enum fax_coding std,
enum endianness order) {
	bitstrm_seek(bs, adv);
	if (std != fax_mmr) {
		uint32_t z;
		do {
			uint32_t bits = bitstrm_peek_32(bs, order);
			z = bit_clz32(bits);
			bitstrm_seek(bs, u32min(z+1, 32));
		} while ((z == 32) && !bs->eof);
	}
}

static bool swap_ink(const uint16_t val) {
	return val < 64;
}

static size_t mh_line(uint8_t *restrict dst, const size_t dst_len,
struct bitstrm *bs, const enum fax_coding std, const enum endianness order) {
	size_t d = 0;
	bool ink = false;
	for (;;) {
		// Max code len is 13 bits, so perform two iterations per peek
		uint32_t bits = bitstrm_peek_32(bs, order);
		uint32_t adv = 0;
		for (int i = 0; i < 2; ++i) {
			uint16_t val;
			bool f = huffman_find(&bits, &adv, &val, ink);
			if (!f || dst_len - d < val) {
				finish_line(bs, adv, std, order);
				return d;
			}
			memset(dst + d, ink, val);
			d += val;
			ink ^= swap_ink(val);
		}
		bitstrm_seek(bs, adv);
	}
	return d;
}


static size_t get_mh_width(struct bitstrm *bs, const enum fax_coding std,
const enum endianness order) {
	size_t w = 0;
	bool ink = false;
	for (;;) {
		uint32_t bits = bitstrm_peek_32(bs, order);
		uint32_t adv = 0;
		for (int i = 0; i < 2; ++i) {
			uint16_t val;
			if (!huffman_find(&bits, &adv, &val, ink)) {
				finish_line(bs, adv, std, order);
				return w;
			}
			w += val;
			ink ^= swap_ink(val);
		}
		bitstrm_seek(bs, adv);
	}
	return w;
}

static void init_fax_bitstrm(struct bitstrm *bs, const struct wuptr mem,
const enum fax_coding std, const enum endianness order) {
	bitstrm_from_wuptr(bs, mem);
	finish_line(bs, 0, std, order);
}

struct wu_st g3_1d_decode(struct wuimg *img, const struct wuptr mem,
const enum endianness order) {
	const enum fax_coding std = fax_mh;
	struct bitstrm bs;
	init_fax_bitstrm(&bs, mem, std, order);
	size_t w = 0;
	for (size_t y = 0; !bs.eof && y < img->h; ++y) {
		uint8_t *dst = img->data + y*img->w;
		w += mh_line(dst, img->w, &bs, std, order);
	}
	return wuerr_partial(w, wuimg_size(img));
}

static struct wu_st g3_1d_decode_le(struct wuimg *img, const struct wuptr mem) {
	return g3_1d_decode(img, mem, little_endian);
}

static void get_g3_1d_dims(struct wuimg *img, const struct wuptr mem,
const enum endianness order) {
	const enum fax_coding std = fax_mh;
	struct bitstrm bs;
	init_fax_bitstrm(&bs, mem, std, order);
	unsigned eol = 0;
	while (!bs.eof) {
		// 6 EOLs mark the end of stream.
		const size_t w = get_mh_width(&bs, std, order);
		if (w) {
			img->w = zumax(img->w, w);
			++img->h;
			eol = 0;
		} else {
			++eol;
			if (eol == 5) {
				break;
			}
		}
	}
}

static void g3_1d_init(struct wuimg *img, const struct wuptr mem,
const enum endianness order) {
	fax_set_img_params(img);
	get_g3_1d_dims(img, mem, order);
}

void g3_1d_default_init(struct wuimg *img, const struct wuptr mem,
enum endianness *order) {
	*order = big_endian;
	g3_1d_init(img, mem, *order);
}


/* ZyXEL */
struct wu_st zyxel_decode(struct wuimg *img, const struct wuptr fax_data) {
	return g3_1d_decode_le(img, fax_data);
}

struct wu_st zyxel_parse(struct wuimg *img, const struct wuptr mem,
struct wuptr *fax_data) {
	/* ZyXEL fax header:
		Offset  Type    Name
		0       u8      Signature[8]
		8       u16     Mystery
		10      u16     Width
		12      u16     ???
		14      u16     ???
		16
	 * When Mystery is non-zero, a mysterious 32-bytes section follows.
	 * Other two fields might be resolution enums
	*/
	struct mparser mp = mp_wuptr(mem);
	const uint8_t sig[] = {'Z', 'y', 'X', 'E', 'L', 0, 2, 0};
	const uint8_t *buf = mp_slice(&mp, 16);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (memcmp(buf, sig, sizeof(sig))) {
		return WUERR_HERE(wu_invalid_signature);
	}
	if (buf_endian16l(buf + 8)) {
		mp_seek_cur(&mp, 32);
	}
	*fax_data = mp_remaining(&mp);
	g3_1d_init(img, *fax_data, little_endian);
	return WU_OK;
}


/* QFX - Quick Link II
https://www.corion.net/fileformats/index.html
*/
struct wu_st qfx_load_page(const struct qfx_desc *desc, struct wuimg *img) {
	return g3_1d_decode_le(img, desc->page_data);
}

struct wu_st qfx_set_page(struct qfx_desc *desc, struct wuimg *img,
const uint16_t i) {
	const size_t s = sizeof(uint32_t);
	const uint32_t start = buf_endian32l(desc->page_offsets + i*s);
	const uint32_t end = buf_endian32l(desc->page_offsets + (i+1)*s);
	if (end > start) {
		mp_seek_set(&desc->mp, start);
		desc->page_data = mp_avail(&desc->mp, end - start);
		g3_1d_init(img, desc->page_data, little_endian);
		return WU_OK;
	}
	return wuerr(wu_invalid_header, "page with negative size");
}

struct wu_st qfx_parse(struct qfx_desc *desc, const struct wuptr mem) {
	/* QFX header:
		Offset  Type    Name
		0       u8      Signature[8]
		8       u16     NrPages               // Up to 375
		10      u16     LastPageScanlines
		12      u16     PageScanlines
		14      u16     Zero?
		16      u16     HorizontalScaling
		18      u16     VerticalScaling
		20      u8      Reserved[12]
		32      u32     PageOffsets[NrPages]
		-       u32     LastPageEnd
		-       u8      Stuff[]
		1536
	*/
	*desc = (struct qfx_desc) {
		.mp = mp_wuptr(mem),
	};
	const uint8_t sig[] = {'Q', 'L', 'I', 'I', 'F', 'A', 'X', ' '};
	const uint8_t *buf = mp_slice(&desc->mp, 32);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (memcmp(buf, sig, sizeof(sig))) {
		return WUERR_HERE(wu_invalid_signature);
	}
	desc->nr_pages = (uint16_t)umin(buf_endian16l(buf + 8), 375);
	desc->page_offsets = mp_slice(&desc->mp,
		(desc->nr_pages + 1u) * sizeof(uint32_t));
	if (desc->page_offsets) {
		return WU_OK;
	}
	return WUERR_HERE(wu_unexpected_eof);
}


/* IFF-FAXX
https://wiki.amigaos.net/wiki/FAXX_IFF_Facsimile_Image
*/
struct wu_st faxx_decode(const struct faxx_desc *desc, struct wuimg *img) {
	const struct wuptr src = mp_avail_at(&desc->mp, desc->mp.pos, desc->len);
	return g3_1d_decode(img, src, big_endian);
}

void faxx_set_image(const struct faxx_desc *desc, struct wuimg *img) {
	if (desc->is_fax3) {
		g3_1d_init(img,
			mp_avail_at(&desc->mp, desc->mp.pos, desc->len),
			big_endian);
	} else {
		img->w = desc->w;
		img->h = desc->h;
		fax_set_img_params(img);
	}
}

static struct wu_st faxx_page(struct iff_state *iff, void *ptr,
const struct iff_chunk chunk) {
	(void)iff;
	struct faxx_desc *desc = ptr;
	desc->len = chunk.len;
	return WU_OK;
}

#define FAXX_MAP_SIZE 3

static struct wu_st faxx_gphd(struct iff_state *iff, void *ptr,
const struct iff_chunk chunk) {
	/* GPHD struct:
		Offset  Type    Name
		0       u16     Width
		2       u16     Height
		4       u16     PageNum
		6       u8      Id[22]
		28      u8      VerticalRes
		29      u8      BitRate
		30      u8      PageWidth
		31      u8      PageHeight
		32      u8      Compression
		33      u8      ErrorCorrection
		34      u8      BinaryTransfer
		35      u8      ScanTimeMs
		36      struct  DateStamp
		48      u8      Padding[10]
		58

	 * DateStamp struct:
		0       u32     DaysSince1978
		4       u32     MinutesPastMidnight
		8       u32     TicksPastMinute
		12
	 * Where 1 tick == 1s/50
	 * Under FAX3, this chunk is named FXHD, and Width and Height are not
	 * reliable (maybe an enum?)
	*/
	enum gphd_vres {
		gphd_vres_std = 0,
		gphd_vres_fine = 1,
	};
	enum gphd_pw {
		gphd_pw_1728 = 0,
		gphd_pw_2048 = 1,
		gphd_pw_2432 = 2,
		gphd_pw_1216 = 3,
		gphd_pw_864 = 4,
	};
	struct faxx_desc *desc = ptr;
	if (chunk.len != 58) {
		return wuerr(wu_invalid_header, "GPHD length != 58");
	} else if (desc->has_gphd) {
		return wuerr(wu_invalid_header, "repeated gphd");
	}
	const uint8_t *buf = mp_slice(&desc->mp, chunk.len);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	}
	desc->has_gphd = true;
	if (desc->is_fax3) {
		/* On my two samples, width is 0xffff and height is 0x0002,
		 * so find out the actual dimensions later. */
	} else {
		desc->w = buf_endian16b(buf);
		desc->h = buf_endian16b(buf + 2);
	}
	desc->gphd.page_num = buf_endian16b(buf + 4);
	memcpy(desc->gphd.id, buf + 6, sizeof(desc->gphd.id));
	switch (buf[28]) {
	case gphd_vres_std: desc->vertical_res = 385; break;
	case gphd_vres_fine: desc->vertical_res = 770; break;
	}
	if (buf[29] <= 5) {
		desc->gphd.bitrate = buf[29];
	}
	switch (buf[30]) {
	case gphd_pw_1728: desc->line_mm = 215; break;
	case gphd_pw_2048: desc->line_mm = 255; break;
	case gphd_pw_2432: desc->line_mm = 303; break;
	case gphd_pw_1216: desc->line_mm = 151; break;
	case gphd_pw_864: desc->line_mm = 107; break;
	}
	switch (buf[31]) {
	case gphd_ph_unlimited:
	case gphd_ph_a4:
	case gphd_ph_b4:
		desc->gphd.page_height = buf[31];
		break;
	}
	switch (buf[32]) {
	case gphd_comp_1d: desc->compression = fax_mh; break;
	case gphd_comp_2d:
	case gphd_comp_2dm:
	case gphd_comp_2du:
	case gphd_comp_none:
		return wuerr(wu_unsupported_feature,
			"only Modified Huffman compression supported");
	default:
		return wuerr(wu_invalid_header, "unknown compression");
	}
	desc->gphd.error_correction = buf[33];
	desc->gphd.binary_transfer = buf[34];
	if (desc->is_fax3) {
		++iff->table;
	} else {
		iff->table_len = FAXX_MAP_SIZE;
	}
	return iff_next_mparser(iff, &desc->mp, chunk);
}

static struct wu_st faxx_fxhd(struct iff_state *iff, void *ptr,
const struct iff_chunk chunk) {
	/* FXHD struct in FAXX (for FAX3, it's named GPHD):
		Offset  Type    Name
		0       u16     Width
		2       u16     Height
		4       u16     LineMili
		6       u16     VerticalRes
		8       u8      Compression
		9       u8      Padding[11]
		20
	*/
	struct faxx_desc *desc = ptr;
	if (chunk.len != 20) {
		return wuerr(wu_invalid_header, "FXHD length != 20");
	} else if (desc->has_fxhd) {
		return wuerr(wu_invalid_header, "repeated FXHD");
	}
	const uint8_t *buf = mp_slice(&desc->mp, chunk.len);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	}
	desc->has_fxhd = true;
	desc->w = buf_endian16b(buf);
	desc->h = buf_endian16b(buf + 2);
	desc->line_mm = buf_endian16b(buf + 4);
	desc->vertical_res = buf_endian16b(buf + 6);
	desc->compression = buf[8];
	switch (desc->compression) {
	case fax_mh:
		iff->table_len = FAXX_MAP_SIZE;
		return iff_next_mparser(iff, &desc->mp, chunk);
	case fax_mr:
	case fax_mmr:
	case fax_none:
		return wuerr(wu_unsupported_feature,
			"only Modified Huffman compression supported");
	}
	return wuerr(wu_invalid_header, "unknown compression method");
}

static const struct iff_table FAXX_MAP[FAXX_MAP_SIZE] = {
	{FOURCC('F', 'X', 'H', 'D'), faxx_fxhd},
	{FOURCC('G', 'P', 'H', 'D'), faxx_gphd},
	{FOURCC('P', 'A', 'G', 'E'), faxx_page},
};

static const struct iff_table FAX3_MAP[] = {
	{FOURCC('F', 'X', 'H', 'D'), faxx_gphd},
	{FOURCC('P', 'A', 'G', 'E'), faxx_page},
};

struct wu_st faxx_init(struct faxx_desc *desc, const struct wuptr mem) {
	*desc = (struct faxx_desc) {
		.mp = mp_wuptr(mem),
	};
	const uint8_t form[4] = {'F', 'O', 'R', 'M'};
	const uint8_t faxx[4] = {'F', 'A', 'X', 'X'};
	const uint8_t fax3[4] = {'F', 'A', 'X', '3'};
	const uint8_t *buf = mp_slice(&desc->mp, 12);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (!memcmp(form, buf, sizeof(form))) {
		desc->is_fax3 = !memcmp(fax3, buf + 8, sizeof(fax3));
		if (desc->is_fax3 || !memcmp(faxx, buf + 8, sizeof(faxx))) {
			struct iff_state state = {
				.table = desc->is_fax3 ? FAX3_MAP : FAXX_MAP,
				.table_len = desc->is_fax3 ? 1 : 2,
				.align_sh = 1,
				.endian = big_endian,
				.user = desc,
			};
			return iff_next_mparser(&state, &desc->mp,
				(struct iff_chunk){0});
		}
	}
	return WUERR_HERE(wu_invalid_signature);
}


/* APF - Async Professional Fax
https://web.archive.org/web/20170102103544/https://turbocontrol.com/FAQ/faxfaq.htm#The%20APF%20file
*/
struct wu_st apf_load_page(const struct apf_desc *desc, struct wuimg *img) {
	return g3_1d_decode_le(img, desc->page_data);
}

struct wu_st apf_next_page(struct apf_desc *desc, struct wuimg *img) {
	/* Page header:
		Offset  Type    Name
		0       u32     DataSize
		4       u16     Flags
		6       u8      Padding[10]
		16
	*/
	const uint8_t *buf = mp_slice(&desc->mp, 16);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	}
	desc->page_data = mp_avail(&desc->mp, buf_endian32l(buf));
	g3_1d_init(img, desc->page_data, little_endian);
	++desc->cur_page;
	return WU_OK;
}

struct wu_st apf_parse(struct apf_desc *desc, const struct wuptr mem) {
	/* APF header:
		Offset  Type    Name
		0       u8      Signature[6]
		6       u32     Timestamp        // DOS format
		10      u8      Zero?
		11      u8      StationID[20]
		31      u8      Padding
		32      u16     NrPages
		34      u32     FirstPageOffset
		38      u8      Padding[46]
		64
	*/
	*desc = (struct apf_desc) {
		.mp = mp_wuptr(mem),
	};
	const uint8_t sig[] = {'A', 'P', 'F', '1', '0', 0x1a};
	const uint8_t *buf = mp_slice(&desc->mp, 64);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (memcmp(buf, sig, sizeof(sig))) {
		return WUERR_HERE(wu_invalid_signature);
	}
	memcpy(desc->station_id, buf + 11, sizeof(desc->station_id));
	desc->nr_pages = buf_endian16l(buf + 32);
	mp_seek_set(&desc->mp, buf_endian32l(buf + 34));
	return WU_OK;
}
