// SPDX-License-Identifier: 0BSD
// SPDX-FileCopyrightText: 2025 kaleido
#include "lib/fax.h"
#include "misc/bit.h"
#include "misc/common.h"
#include "misc/iff.h"
#include "misc/math.h"
#include "misc/time.h"

// Generated by fax.py
#include "fax_table.h"

// TODO: Find Group4/T.6 streams

/* Tradition is that 0=white and 1=black, as if putting ink to paper.
 * If enabled, use 1=white and 0=black instead, as if emitting light. This lets
 * us pass unscaled pixel values when converting to PAM and JPEG-XL. */
static const bool MIN_IS_BLACK = true;

const char * fax_coding_str(enum fax_coding coding) {
	switch (coding) {
	case fax_none: return "No compression";
	case fax_mh: return "Modified Huffman";
	case fax_mr: return "Modified READ";
	case fax_mmr: return "Modified Modified READ";
	}
	return "???";
}

const char * gphd_ph_str(enum gphd_ph ph) {
	switch (ph) {
	case gphd_ph_unlimited: return "Unlimited";
	case gphd_ph_a4: return "A4 PAGE 297 mm";
	case gphd_ph_b4: return "B4 PAGE 364 mm";
	}
	return "???";
}

static void fax_set_img_params(struct wuimg *img) {
	img->channels = 1;
	img->bitdepth = 8;
	img->bitrange = 1;
	img->cs.invert = !MIN_IS_BLACK;
}

static uint32_t huff_get_pair(const uint32_t bits, const uint32_t nr,
const bool ink, const bool level2, const uint32_t prev_val, uint16_t *val) {
	const uint32_t idx = ((uint32_t)level2 << FAX_LEVEL1_BITS)
		+ (prev_val << FAX_LEVEL2_BITS)
		+ (bits >> (32 - nr))
		+ (ink ? FAX_BLACK_OFFSET : FAX_WHITE_OFFSET);
	*val = fax_huffman_get_val(FAX_HUFFMAN_TABLE[idx]);
	return fax_huffman_get_bits(FAX_HUFFMAN_TABLE[idx]);
}

static uint32_t huffman_find(uint32_t bits, uint16_t *val, bool ink) {
	ink ^= MIN_IS_BLACK;
	uint32_t adv = huff_get_pair(bits, FAX_LEVEL1_BITS, ink, false, 0, val);
	if (!adv) {
		adv = huff_get_pair(bits << FAX_LEVEL1_BITS, FAX_LEVEL2_BITS,
			ink, true, *val, val);
		if (adv) {
			adv += FAX_LEVEL1_BITS;
		}
	}
	return adv;
}

static uint32_t skip_zeros(struct bitstrm *bs, const enum endianness order) {
	uint32_t bits = bitstrm_peek_32(bs, order);
	uint32_t z = bit_clz32(bits);
	bitstrm_seek(bs, u32min(z+1, 32));
	return z;
}

static void next_eol(struct bitstrm *bs, enum fax_coding std,
enum endianness order) {
	if (std != fax_mmr) {
		uint32_t z;
		do {
			z = skip_zeros(bs, order);
		} while (z < 11 && !bs->eof);
		while (z == 32 && !bs->eof) {
			z = skip_zeros(bs, order);
		}
	}
}

static bool swap_ink(const uint16_t val) {
	return val < 64;
}

static size_t write_line(uint8_t *restrict dst, const size_t start,
const bool ink, const size_t len) {
	memset(dst + start, ink, len);
	return start + len;
}

static size_t write_region(uint8_t *restrict dst, const size_t start,
const bool ink, const size_t end) {
	return write_line(dst, start, ink, end - start);
}

static size_t mh_line(uint8_t *restrict dst, const size_t dst_len,
struct bitstrm *bs, const enum endianness order) {
	size_t d = 0;
	bool ink = MIN_IS_BLACK;
	for (;;) {
		// Max code len is 13 bits, so perform two iterations per peek
		uint32_t bits = bitstrm_peek_32(bs, order);
		uint32_t adv = 0;
		for (int i = 0; i < 2; ++i) {
			uint16_t val;
			uint32_t read = huffman_find(bits, &val, ink);
			if (!read || dst_len - d < val) {
				goto mh_exit;
			}
			bits <<= read;
			adv += read;
			d = write_line(dst, d, ink, val);
			ink ^= swap_ink(val);
		}
		bitstrm_seek(bs, adv);
	}
mh_exit:
	write_region(dst, d, MIN_IS_BLACK, dst_len);
	return d;
}

static size_t mr_next_change(const uint8_t *restrict ref, size_t i,
const size_t end, const bool cur, const size_t dt) {
	while (end - i > dt && ref[i] == cur) {
		++i;
	}
	return i;
}

static size_t mr_find_b1(const uint8_t *restrict ref, size_t i,
const size_t end, const bool cur, const size_t dt) {
	return mr_next_change(ref,
		mr_next_change(ref, i, end, !cur, dt),
		end, cur, dt);
}

static size_t mr_find_b2(const uint8_t *restrict ref, size_t i,
const size_t end, const bool cur) {
	if (i) {
		i = mr_next_change(ref, i, end, !cur, 0);
	}
	return mr_next_change(ref,
		mr_next_change(ref, i, end, cur, 0),
		end, !cur, 0);
}

static size_t mr_line(uint8_t *dst, const uint8_t *ref, const size_t dst_len,
struct bitstrm *bs, const enum endianness order) {
	size_t d = 0;
	bool ink = MIN_IS_BLACK;
	while (d < dst_len) {
		uint32_t bits = bitstrm_peek_32(bs, order);
		uint32_t adv = bit_clz32(bits) + 1;
		switch (adv) {
		case 4: // pass mode
			d = write_region(dst, d, ink,
				mr_find_b2(ref, d, dst_len, ink));
			break;
		case 3: // horizontal mode
			;int swaps = 0;
			while (swaps < 2) {
				bitstrm_seek(bs, adv);
				bits = bitstrm_peek_32(bs, order);
				adv = 0;
				for (int i = 0; swaps < 2 && i < 2; ++i) {
					uint16_t val;
					uint32_t read = huffman_find(bits,
						&val, ink);
					if (!read || dst_len - d < val) {
						goto mr_exit;
					}
					bits <<= read;
					adv += read;
					d = write_line(dst, d, ink, val);
					bool s = swap_ink(val);
					ink ^= s;
					swaps += s;
				}
			}
			break;
		case 1: // vertical 0
			d = write_region(dst, d, ink,
				mr_find_b1(ref, d, dst_len, ink, 0));
			ink ^= 1;
			break;
		case 2: // vertical 1,2,3
		case 5:
		case 6:
			;size_t dt;
			switch (adv) {
			case 2: dt = 1; break;
			case 5: dt = 2; break;
			case 6: dt = 3; break;
			}
			const bool positive = bits << adv >> 31;
			++adv;
			size_t b1 = mr_find_b1(ref, d, dst_len, ink, dt);
			if (positive) {
				if (dst_len - b1 < dt) {
					break;
				}
				b1 += dt;
			} else {
				if (b1 - d < dt) {
					break;
				}
				b1 -= dt;
			}
			d = write_region(dst, d, ink, b1);
			ink ^= 1;
			break;
		default:
			goto mr_exit;
		}
		bitstrm_seek(bs, adv);
	}
mr_exit:
	write_region(dst, d, MIN_IS_BLACK, dst_len);
	return d;
}

static bool next_line_coding(struct bitstrm *bs, enum fax_coding std,
enum endianness order, bool first_line, bool *is_mh) {
	*is_mh = true;
	do {
		next_eol(bs, std, order);
		if (std == fax_mr) {
			*is_mh = bitstrm_next(bs, order);
			if (*is_mh || !first_line) {
				return true;
			}
		} else {
			return true;
		}
	} while (!bs->eof);
	return false;
}

static size_t fax_line_no_eol(uint8_t *restrict dst,
const uint8_t *restrict ref, const size_t dst_len, struct bitstrm *bs,
enum endianness order, bool is_mh) {
	return is_mh
		? mh_line(dst, dst_len, bs, order)
		: mr_line(dst, ref, dst_len, bs, order);
}

static size_t fax_line(uint8_t *restrict dst, const uint8_t *restrict ref,
const size_t dst_len, const bool first_line, struct bitstrm *bs,
enum fax_coding std, enum endianness order) {
	bool mh;
	if (!next_line_coding(bs, std, order, first_line, &mh)) {
		return 0;
	}
	return fax_line_no_eol(dst, ref, dst_len, bs, order, mh);
}

struct wu_st g3_decode(struct wuimg *img, const struct wuptr mem,
const enum fax_coding std, const enum endianness order) {
	struct bitstrm bs;
	bitstrm_from_wuptr(&bs, mem);
	size_t w = 0;
	for (size_t y = 0; !bs.eof && y < img->h; ++y) {
		uint8_t *dst = img->data + y*img->w;
		w += fax_line(dst, dst - img->w, img->w, !y,
			&bs, std, order);
	}
	return wuerr_partial(w, wuimg_size(img));
}

struct wu_st g3_1d_decode(struct wuimg *img, const struct wuptr mem,
const enum endianness order) {
	return g3_decode(img, mem, fax_mh, order);
}

static struct wu_st g3_1d_decode_le(struct wuimg *img, const struct wuptr mem) {
	return g3_1d_decode(img, mem, little_endian);
}

static bool get_g3_dims(struct wuimg *img, const struct wuptr mem,
const enum fax_coding std, const enum endianness order) {
	const size_t buf_size = 2560; // longest huffman length value
	uint8_t *buf = calloc(buf_size, 2);
	if (!buf) {
		return false;
	}
	/* We don't expect any fax to be this small, it's just to make the
	 * code give up quicker. */
	const size_t min_size = 32;
	struct bitstrm bs;
	bitstrm_from_wuptr(&bs, mem);
	img->w = 0;
	img->h = 0;
	size_t prev_w = 0;
	unsigned eol = 0;
	unsigned badness = 0;
	bool ok = true;
	while (!bs.eof) {
		bool mh;
		if (!next_line_coding(&bs, std, order, !img->h, &mh)) {
			break;
		}
		const size_t w = fax_line_no_eol(
			buf + (img->h & 1) * buf_size,
			buf + !(img->h & 1) * buf_size,
			(mh ? buf_size : img->w),
			&bs, order, mh);
		if (w) {
			badness += (img->w < min_size) | (prev_w != w);
			prev_w = w;
			img->w = zumax(img->w, w);
			img->h += eol + 1;
			eol = 0;
			if (badness > (img->h+min_size)/2) {
				ok = false;
				break;
			}
		} else {
			// 6 EOLs mark the end of stream.
			++eol;
			if (eol == 5) {
				break;
			}
		}
	}
	free(buf);
	return ok && img->h >= min_size;
}

static bool g3_1d_init(struct wuimg *img, const struct wuptr mem,
const enum endianness order) {
	fax_set_img_params(img);
	return get_g3_dims(img, mem, fax_mh, order);
}

bool g3_identify(struct wuimg *img, const struct wuptr mem,
enum fax_coding *out_std, enum endianness *out_end) {
	const enum fax_coding std[] = {
		// test MH first as it's more restrictive
		fax_mh, fax_mr,
	};
	const enum endianness end[] = {
		big_endian, little_endian,
	};
	fax_set_img_params(img);
	for (size_t s = 0; s < ARRAY_LEN(std); ++s) {
		for (size_t e = 0; e < ARRAY_LEN(end); ++e) {
			if (get_g3_dims(img, mem, std[s], end[e])) {
				*out_std = std[s];
				*out_end = end[e];
				return true;
			}
		}
	}
	return false;
}


/* ZyXEL */
struct wu_st zyxel_decode(struct wuimg *img, const struct wuptr fax_data) {
	return g3_1d_decode_le(img, fax_data);
}

struct wu_st zyxel_parse(struct wuimg *img, const struct wuptr mem,
struct wuptr *fax_data) {
	/* ZyXEL fax header:
		Offset  Type    Name
		0       u8      Signature[8]
		8       u16     Mystery
		10      u16     Width
		12      u16     ???
		14      u16     ???
		16
	 * When Mystery is non-zero, a mysterious 32-bytes section follows.
	*/
	struct mparser mp = mp_wuptr(mem);
	const uint8_t sig[] = {'Z', 'y', 'X', 'E', 'L', 0, 2, 0};
	const uint8_t *buf = mp_slice(&mp, 16);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (memcmp(buf, sig, sizeof(sig))) {
		return WUERR_HERE(wu_invalid_signature);
	}
	if (buf_endian16l(buf + 8)) {
		mp_seek_cur(&mp, 32);
	}
	*fax_data = mp_remaining(&mp);
	g3_1d_init(img, *fax_data, little_endian);
	return WU_OK;
}


/* QFX - Quick Link II
https://www.corion.net/fileformats/index.html
*/
struct wu_st qfx_load_page(const struct qfx_desc *desc, struct wuimg *img) {
	return g3_1d_decode_le(img, desc->page_data);
}

struct wu_st qfx_set_page(struct qfx_desc *desc, struct wuimg *img,
const uint16_t i) {
	const size_t s = sizeof(uint32_t);
	const uint32_t start = buf_endian32l(desc->page_offsets + i*s);
	const uint32_t end = buf_endian32l(desc->page_offsets + (i+1)*s);
	if (end > start) {
		mp_seek_set(&desc->mp, start);
		desc->page_data = mp_avail(&desc->mp, end - start);
		g3_1d_init(img, desc->page_data, little_endian);
		return WU_OK;
	}
	return wuerr(wu_invalid_header, "page with negative size");
}

struct wu_st qfx_parse(struct qfx_desc *desc, const struct wuptr mem) {
	/* QFX header:
		Offset  Type    Name
		0       u8      Signature[8]
		8       u16     NrPages               // Up to 375
		10      u16     LastPageScanlines
		12      u16     PageScanlines
		14      u16     Zero?
		16      u16     HorizontalScaling
		18      u16     VerticalScaling
		20      u8      Reserved[12]
		32      u32     PageOffsets[NrPages]
		-       u32     LastPageEnd
		-       u8      Stuff[]
		1536
	*/
	*desc = (struct qfx_desc) {
		.mp = mp_wuptr(mem),
	};
	const uint8_t sig[] = {'Q', 'L', 'I', 'I', 'F', 'A', 'X', ' '};
	const uint8_t *buf = mp_slice(&desc->mp, 32);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (memcmp(buf, sig, sizeof(sig))) {
		return WUERR_HERE(wu_invalid_signature);
	}
	desc->nr_pages = (uint16_t)umin(buf_endian16l(buf + 8), 375);
	desc->page_offsets = mp_slice(&desc->mp,
		(desc->nr_pages + 1u) * sizeof(uint32_t));
	if (desc->page_offsets) {
		return WU_OK;
	}
	return WUERR_HERE(wu_unexpected_eof);
}


/* IFF-FAXX
https://wiki.amigaos.net/wiki/FAXX_IFF_Facsimile_Image
*/
struct wu_st faxx_decode(const struct faxx_desc *desc, struct wuimg *img) {
	const struct wuptr src = mp_avail_at(&desc->mp, desc->mp.pos, desc->len);
	return g3_decode(img, src, desc->compression, big_endian);
}

void faxx_set_image(const struct faxx_desc *desc, struct wuimg *img) {
	fax_set_img_params(img);
	if (desc->is_fax3) {
		get_g3_dims(img,
			mp_avail_at(&desc->mp, desc->mp.pos, desc->len),
			desc->compression, big_endian);
	} else {
		img->w = desc->w;
		img->h = desc->h;
	}
}

static struct wu_st faxx_page(struct iff_state *iff, void *ptr,
const struct iff_chunk chunk) {
	(void)iff;
	struct faxx_desc *desc = ptr;
	desc->len = chunk.len;
	return WU_OK;
}

#define FAXX_MAP_SIZE 3

static struct wu_st faxx_gphd(struct iff_state *iff, void *ptr,
const struct iff_chunk chunk) {
	/* GPHD struct:
		Offset  Type    Name
		0       u16     Width
		2       u16     Height
		4       u16     PageNum
		6       u8      Id[22]
		28      u8      VerticalRes
		29      u8      BitRate
		30      u8      PageWidth
		31      u8      PageHeight
		32      u8      Compression
		33      u8      ErrorCorrection
		34      u8      BinaryTransfer
		35      u8      ScanTimeMs
		36      struct  DateStamp
		48      u8      Padding[10]
		58

	 * DateStamp struct:
		0       u32     DaysSince1978
		4       u32     MinutesPastMidnight
		8       u32     TicksPastMinute
		12
	 * Where 1 tick == 1s/50
	 * Under FAX3, this chunk is named FXHD, and Width and Height are not
	 * reliable (maybe an enum?)
	*/
	enum gphd_vres {
		gphd_vres_std = 0,
		gphd_vres_fine = 1,
	};
	enum gphd_pw {
		gphd_pw_1728 = 0,
		gphd_pw_2048 = 1,
		gphd_pw_2432 = 2,
		gphd_pw_1216 = 3,
		gphd_pw_864 = 4,
	};
	struct faxx_desc *desc = ptr;
	if (chunk.len != 58) {
		return wuerr(wu_invalid_header, "GPHD length != 58");
	} else if (desc->has_gphd) {
		return wuerr(wu_invalid_header, "repeated gphd");
	}
	const uint8_t *buf = mp_slice(&desc->mp, chunk.len);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	}
	desc->has_gphd = true;
	if (desc->is_fax3) {
		/* On my two samples, width is 0xffff and height is 0x0002,
		 * so find out the actual dimensions later. */
	} else {
		desc->w = buf_endian16b(buf);
		desc->h = buf_endian16b(buf + 2);
	}
	desc->gphd.page_num = buf_endian16b(buf + 4);
	memcpy(desc->gphd.id, buf + 6, sizeof(desc->gphd.id));
	switch (buf[28]) {
	case gphd_vres_std: desc->vertical_res = 385; break;
	case gphd_vres_fine: desc->vertical_res = 770; break;
	}
	if (buf[29] <= 5) {
		desc->gphd.bitrate = buf[29];
	}
	switch (buf[30]) {
	case gphd_pw_1728: desc->line_mm = 215; break;
	case gphd_pw_2048: desc->line_mm = 255; break;
	case gphd_pw_2432: desc->line_mm = 303; break;
	case gphd_pw_1216: desc->line_mm = 151; break;
	case gphd_pw_864: desc->line_mm = 107; break;
	}
	switch (buf[31]) {
	case gphd_ph_unlimited:
	case gphd_ph_a4:
	case gphd_ph_b4:
		desc->gphd.page_height = buf[31];
		break;
	}
	switch (buf[32]) {
	case gphd_comp_1d: desc->compression = fax_mh; break;
	case gphd_comp_2d: desc->compression = fax_mr; break;
	case gphd_comp_2dm:
	case gphd_comp_2du:
	case gphd_comp_none:
		return wuerr(wu_unsupported_feature,
			"only Modified Huffman and Modified READ supported");
	default:
		return wuerr(wu_invalid_header, "unknown compression");
	}
	desc->gphd.error_correction = buf[33];
	desc->gphd.binary_transfer = buf[34];
	if (desc->is_fax3) {
		++iff->table;
	} else {
		iff->table_len = FAXX_MAP_SIZE;
	}
	return iff_next_mparser(iff, &desc->mp, chunk);
}

static struct wu_st faxx_fxhd(struct iff_state *iff, void *ptr,
const struct iff_chunk chunk) {
	/* FXHD struct in FAXX (for FAX3, it's named GPHD):
		Offset  Type    Name
		0       u16     Width
		2       u16     Height
		4       u16     LineMili
		6       u16     VerticalRes
		8       u8      Compression
		9       u8      Padding[11]
		20
	*/
	struct faxx_desc *desc = ptr;
	if (chunk.len != 20) {
		return wuerr(wu_invalid_header, "FXHD length != 20");
	} else if (desc->has_fxhd) {
		return wuerr(wu_invalid_header, "repeated FXHD");
	}
	const uint8_t *buf = mp_slice(&desc->mp, chunk.len);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	}
	desc->has_fxhd = true;
	desc->w = buf_endian16b(buf);
	desc->h = buf_endian16b(buf + 2);
	desc->line_mm = buf_endian16b(buf + 4);
	desc->vertical_res = buf_endian16b(buf + 6);
	desc->compression = buf[8];
	switch (desc->compression) {
	case fax_mh:
	case fax_mr:
		iff->table_len = FAXX_MAP_SIZE;
		return iff_next_mparser(iff, &desc->mp, chunk);
	case fax_mmr:
	case fax_none:
		return wuerr(wu_unsupported_feature,
			"only Modified Huffman and Modified READ supported");
	}
	return wuerr(wu_invalid_header, "unknown compression method");
}

static const struct iff_table FAXX_MAP[FAXX_MAP_SIZE] = {
	{FOURCC('F', 'X', 'H', 'D'), faxx_fxhd},
	{FOURCC('G', 'P', 'H', 'D'), faxx_gphd},
	{FOURCC('P', 'A', 'G', 'E'), faxx_page},
};

static const struct iff_table FAX3_MAP[] = {
	{FOURCC('F', 'X', 'H', 'D'), faxx_gphd},
	{FOURCC('P', 'A', 'G', 'E'), faxx_page},
};

struct wu_st faxx_init(struct faxx_desc *desc, const struct wuptr mem) {
	*desc = (struct faxx_desc) {
		.mp = mp_wuptr(mem),
	};
	const uint8_t form[4] = {'F', 'O', 'R', 'M'};
	const uint8_t faxx[4] = {'F', 'A', 'X', 'X'};
	const uint8_t fax3[4] = {'F', 'A', 'X', '3'};
	const uint8_t *buf = mp_slice(&desc->mp, 12);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (!memcmp(form, buf, sizeof(form))) {
		desc->is_fax3 = !memcmp(fax3, buf + 8, sizeof(fax3));
		if (desc->is_fax3 || !memcmp(faxx, buf + 8, sizeof(faxx))) {
			struct iff_state state = {
				.table = desc->is_fax3 ? FAX3_MAP : FAXX_MAP,
				.table_len = desc->is_fax3 ? 1 : 2,
				.align_sh = 1,
				.endian = big_endian,
				.user = desc,
			};
			return iff_next_mparser(&state, &desc->mp,
				(struct iff_chunk){0});
		}
	}
	return WUERR_HERE(wu_invalid_signature);
}


/* APF - Async Professional Fax
https://web.archive.org/web/20170102103544/https://turbocontrol.com/FAQ/faxfaq.htm#The%20APF%20file
*/
struct wu_st apf_load_page(const struct apf_desc *desc, struct wuimg *img) {
	if (desc->line_len) {
		struct mparser mp = mp_wuptr(desc->page_data);
		size_t r = 0;
		for (size_t y = 0; y < img->h; ++y) {
			struct bitstrm bs;
			bitstrm_from_wuptr(&bs,
				mp_avail(&mp, buf_endian16l(mp_slice(&mp, 2))));
			uint8_t *dst = img->data + y*img->w;
			r += fax_line(dst, NULL, img->w, true, &bs, fax_mh,
				little_endian);
		}
		return wuerr_partial(r, wuimg_size(img));
	}
	return g3_1d_decode_le(img, desc->page_data);
}

struct wu_st apf_next_page(struct apf_desc *desc, struct wuimg *img) {
	/* Page header:
		Offset  Type    Name
		0       u32     DataSize
		4       u16     Flags
		6       u8      Padding[10]
		16
	*/
	const uint8_t *buf = mp_slice(&desc->mp, 16);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	}
	desc->page_data = mp_avail(&desc->mp, buf_endian32l(buf));
	const uint16_t flags = buf_endian16l(buf + 4);
	desc->line_len = flags & 0x4;
	desc->high_res = flags & 0x1;
	++desc->cur_page;
	if (desc->line_len) {
		fax_set_img_params(img);
		// Not sure this is correct
		img->w = (flags & 0x2) ? 2048 : 1728;
		img->h = 0;
		size_t pos = 0;
		while (desc->page_data.len - pos > 2) {
			uint16_t len = buf_endian16l(desc->page_data.ptr + pos);
			pos += 2;
			++img->h;
			if (desc->page_data.len - pos < len) {
				return WU_OK;
			}
			pos += len;
		}
		img->h -= (bool)img->h; // last line is 6 EOLs
	} else {
		g3_1d_init(img, desc->page_data, little_endian);
	}
	return WU_OK;
}

struct wu_st apf_parse(struct apf_desc *desc, const struct wuptr mem) {
	/* APF header:
		Offset  Type    Name
		0       u8      Signature[6]
		6       u32     Timestamp        // DOS format
		10      u8      Zero?
		11      u8      StationID[20]
		31      u8      Padding
		32      u16     NrPages
		34      u32     FirstPageOffset
		38      u8      Padding[46]
		64
	*/
	*desc = (struct apf_desc) {
		.mp = mp_wuptr(mem),
	};
	const uint8_t sig[] = {'A', 'P', 'F', '1', '0', 0x1a};
	const uint8_t *buf = mp_slice(&desc->mp, 64);
	if (!buf) {
		return WUERR_HERE(wu_unexpected_eof);
	} else if (memcmp(buf, sig, sizeof(sig))) {
		return WUERR_HERE(wu_invalid_signature);
	}
	desc->timestamp = time_from_dos((time_t)buf_endian32l(buf + 6));
	memcpy(desc->station_id, buf + 11, sizeof(desc->station_id));
	desc->nr_pages = buf_endian16l(buf + 32);
	mp_seek_set(&desc->mp, buf_endian32l(buf + 34));
	return WU_OK;
}
