# SPDX-License-Identifier: 0BSD
# SPDX-FileCopyrightText: 2020 kaleido
option('aliaspix', type : 'feature', description : 'AliasPIX and Vivid')
option('ant', type : 'feature', description : 'Studio e.Go ANT Image')
option('atari', type : 'feature', description : 'Atari image formats')
option('bethesda', type : 'feature', description : 'Bethesda BSI and GXA')
option('bmz', type : 'feature', description : 'GSD engine compressed BMP, requires DIB')
option('c', type : 'feature', description : 'C code formats: DEGAS Elite Icon, XBM')
option('c64', type : 'feature', description : 'C64 image formats')
option('cbg', type : 'feature', description : 'BGI/Ethornell CompressedBG (v1)')
option('chunsoft', type : 'feature', description : 'Chunsoft AT6P and SIR0 sprites')
option('cisrle', type : 'feature', description : 'CompuServe RLE')
option('croteam', type : 'feature', description : 'Croteam Texture (TBN)')
option('dib', type : 'feature', description : 'DIB family (BMP, ICO, and CUR)')
option('dpx', type : 'feature', description : 'Digital Picture Exchange')
option('dvm', type : 'feature', description : 'Magic Software DVM')
option('ea', type : 'feature', description : 'Electronic Arts FFN & SFN')
option('eclipse', type : 'feature', description : 'Eclipse TILE')
option('elecbyte', type : 'feature', description : 'Elecbyte M.U.G.E.N. formats')
option('g00', type : 'feature', description : 'RealLive engine image')
option('gp4', type : 'feature', description : 'elf\'s AI5 engine GP4')
option('gpc', type : 'feature', description : 'IDES/Fairytale PC-98 visual novel image')
option('hg3', type : 'feature', description : 'CatSystem engine image')
option('hel', type : 'feature', description : 'Herahera Animation (HEL)')
option('ilbm', type : 'feature', description : 'IFF/ILBM image')
option('jam', type : 'feature', description : 'Aladdin JAM')
option('kyg', type : 'feature', description : 'Kyss graphics format')
option('lwi', type : 'feature', description : 'LightWork Image')
option('mac', type : 'feature', description : 'MacPaint image')
option('mag', type : 'feature', description : 'MAG/MAKI02 image')
option('maki', type : 'feature', description : 'MAKI01 image')
option('mgx', type : 'feature', description : 'Micrografx ICN')
option('msx', type : 'feature', description : 'MSX-BASIC image family')
option('nokia', type : 'feature', description : 'Nokia NOL and NGG')
option('pcf', type : 'feature', description : 'PCF bitmap fonts')
option('pcx', type : 'feature', description : 'PC Paintbrush PCX')
option('pdt', type : 'feature', description : 'RealLive engine image')
option('pgx', type : 'feature', description : 'GLib2 engine image')
option('pi', type : 'feature', description : 'Yanagisawa\'s Pi image')
option('pi1', type : 'feature', description : 'Pi1 DEGAS image')
option('pic', type : 'feature', description : 'Yanagisawa\'s PIC image')
option('pic2', type : 'feature', description : 'Yanagisawa\'s PIC2 image')
option('pictor', type : 'feature', description : 'PCPaint PICtor')
option('pmg', type : 'feature', description : 'Print Magic Graphic')
option('pnm', type : 'feature', description : 'PNM family')
option('prt', type : 'feature', description : 'Kid engine image')
option('px', type : 'feature', description : 'Leaf PX image')
option('q4', type : 'feature', description : 'Q4 image (XLD4)')
option('qoi', type : 'feature', description : 'QuiteOK image')
option('quake', type : 'feature', description : 'id Software Sprite (IDSP) and Quake LMP')
option('sgf', type : 'feature', description : 'Somera Graphic Format')
option('sgi', type : 'feature', description : 'Silicon Graphics Image')
option('siff', type : 'feature', description : 'SIFF sprite (PXAN)')
option('signum', type : 'feature', description : 'Signum! IMC')
option('sixel', type : 'feature', description : 'SIXEL terminal graphics')
option('skyroads', type : 'feature', description : 'SkyRoads LZS graphics')
option('spooky', type : 'feature', description : 'Spooky Sprites TRS and TRE')
option('sun', type : 'feature', description : 'Sun Raster')
option('tga', type : 'feature', description : 'Truevision TGA (TARGA)')
option('tim', type : 'feature', description : 'PlayStation image')
option('tlg', type : 'feature', description : 'KiriKiri engine image')
option('txf', type : 'feature', description : 'TexFont Texture Mapped Font')
option('utahrle', type : 'feature', description : 'Utah RLE')
option('wbmp', type : 'feature', description : 'Wireless Bitmap')
option('wgtspr', type : 'feature', description : 'WGT Sprite')
option('wpx', type : 'feature', description : 'Wild-Bug engine image')
option('xcursor', type : 'feature', description : 'X11 cursor')
option('xwd', type : 'feature', description : 'X11 Window Dump')
option('xyz', type : 'feature', description : 'RPG Maker image')

option('disable_external', type : 'boolean', value : false, description : 'Disable all external formats')
option('avif', type : 'feature', description : 'via libavif')
option('flif', type : 'feature', description : 'via libflif')
option('gif', type : 'feature', description : 'via libgif')
option('heif', type : 'feature', description : 'via libheif, supports avif if libavif is not used')
option('jbig', type : 'feature', description : 'via libjbig')
option('jbig2', type : 'feature', description : 'via libjbig2dec')
option('jpeg', type : 'feature', description : 'JPEG and MPO, via libjpeg')
option('jpeg2000', type : 'feature', description : 'via libopenjp2')
option('jpegls', type : 'feature', description : 'via libcharls')
option('jpegxl', type : 'feature', description : 'via libjxl')
option('lerc', type : 'feature', description : 'via liblerc')
option('png', type : 'feature', description : 'via libpng')
option('raw', type : 'feature', description : 'via libraw')
option('svg', type : 'feature', description : 'via librsvg')
option('tiff', type : 'feature', description : 'via libtiff')
option('webp', type : 'feature', description : 'via libwebp and libwebpdemux')

option('window_glfw', type : 'feature', description : 'GLFW backend, for X11 and Wayland')
option('window_drm', type : 'feature', description : 'DRM/KMS backend')
option('window_wayland', type : 'feature', description : 'Wayland native backend')
