option('flif', type : 'feature', description : 'via libflif')
option('gif', type : 'feature', description : 'via libgif')
option('heif', type : 'feature', description : 'via libheif')
option('jbig', type : 'feature', description : 'via libjbig')
option('jpeg', type : 'feature', description : 'via libjpeg')
option('jpeg2000', type : 'feature', description : 'via libopenjp2')
option('png', type : 'feature', description : 'via libpng')
option('raw', type : 'feature', description : 'via libraw')
option('svg', type : 'feature', description : 'via librsvg')
option('tiff', type : 'feature', description : 'via libtiff')
option('webp', type : 'feature', description : 'via libwebp and libwebpdemux')

option('avs', type : 'feature')
option('bmp', type : 'feature')
option('mac', type : 'feature')
option('pcx', type : 'feature')
option('pgx', type : 'feature')
option('pi', type : 'feature')
option('pnm', type : 'feature')
option('sgi', type : 'feature')
option('sixel', type : 'feature')
option('sun', type : 'feature')
option('tga', type : 'feature')
option('wbmp', type : 'feature')
option('xbm', type : 'feature', value : 'disabled')
