# SPDX-License-Identifier: 0BSD
option('avs', type : 'feature')
option('bmz', type : 'feature', description : 'GSD engine compressed BMP, requires DIB')
option('c64', type : 'feature', description : 'C64 image formats')
option('degas', type : 'feature', description : 'DEGAS image formats')
option('dib', type : 'feature', description : 'DIB family (BMP, ICO, and CUR)')
option('dpx', type : 'feature')
option('farbfeld', type : 'feature')
option('g00', type : 'feature', description : 'RealLive engine image')
option('hg3', type : 'feature', description : 'CatSystem engine image')
option('ilbm', type : 'feature', description : 'IFF/ILBM image')
option('mac', type : 'feature', description : 'MacPaint image')
option('mag', type : 'feature', description : 'MAG/MAKI02 image')
option('maki', type : 'feature', description : 'MAKI01 image')
option('msx', type : 'feature', description : 'MSX-BASIC image family')
option('pcf', type : 'feature', description : 'PCF bitmap fonts')
option('pcx', type : 'feature')
option('pdt', type : 'feature', description : 'RealLive engine image')
option('pgx', type : 'feature', description : 'GLib2 engine image')
option('pi', type : 'feature', description : 'Yanagisawa\'s Pi image')
option('pi1', type : 'feature', description : 'Pi1 DEGAS image')
option('pic', type : 'feature', description : 'Yanagisawa\'s PIC image')
option('pic2', type : 'feature', description : 'Yanagisawa\'s PIC2 image')
option('pictor', type : 'feature')
option('pnm', type : 'feature', description : 'PNM family')
option('prt', type : 'feature', description : 'Kid engine image')
option('px', type : 'feature', description : 'Leaf PX image')
option('q4', type : 'feature', description : 'XLD4(Q4) image')
option('qoi', type : 'feature')
option('sgi', type : 'feature')
option('sixel', type : 'feature')
option('sun', type : 'feature')
option('tga', type : 'feature')
option('tim', type : 'feature', description : 'PlayStation image')
option('tlg', type : 'feature', description : 'KiriKiri engine image')
option('wbmp', type : 'feature')
option('wpx', type : 'feature', description : 'Wild-Bug engine image')
option('xbm', type : 'feature')
option('xcursor', type : 'feature')
option('xwd', type : 'feature')
option('xyz', type : 'feature', description : 'RPG Maker image')

option('disable_external', type : 'boolean', value : false, description : 'Disable all external formats')
option('avif', type : 'feature', description : 'via libavif')
option('flif', type : 'feature', description : 'via libflif')
option('gif', type : 'feature', description : 'via libgif')
option('heif', type : 'feature', description : 'via libheif, supports avif if libavif is not used')
option('jbig', type : 'feature', description : 'via libjbig')
option('jpeg', type : 'feature', description : 'via libjpeg')
option('jpeg2000', type : 'feature', description : 'via libopenjp2')
option('jpegls', type : 'feature', description : 'via libcharls')
option('jpegxl', type : 'feature', description : 'via libjxl')
option('Lerc', type : 'feature', description : 'via liblerc')
option('png', type : 'feature', description : 'via libpng')
option('raw', type : 'feature', description : 'via libraw')
option('svg', type : 'feature', description : 'via librsvg')
option('tiff', type : 'feature', description : 'via libtiff')
option('webp', type : 'feature', description : 'via libwebp and libwebpdemux')

option('window_glfw', type : 'feature', description : 'GLFW backend, for X11 and Wayland')
option('window_drm', type : 'feature', description : 'DRM/KMS backend')
option('window_wayland', type : 'feature', description : 'Wayland native backend')

option('compile_fuzzer', type : 'boolean', value : false, description : 'Compile fuzzer binary')
