#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>

#include <sys/stat.h>

#include "dec.h"
#include "rast_utils.h"

/*

This file is included by dec_maps.c, generated by dec_comptime -m

*/

static int fmaskmagiccmp(const void *restrict m1, const void *restrict m2) {
	const unsigned char *restrict magic1 = m1;
	const struct fmt_magic *restrict magic2 = m2;
	int diff = 0;
	for (size_t i = 0; i < MAX_MAG_LEN; ++i) {
		const unsigned char m = magic2->and_mask[i];
		diff = (magic1[i] & m) - (magic2->bytes[i] & m);
		if (diff) {
			break;
		}
	}
	return diff;
}

static int fextcmp(const void *restrict e1, const void *restrict e2) {
	const char *restrict ext1 = e1;
	const struct fmt_ext *restrict ext2 = e2;
	return memcmp(ext1, ext2->ext, MAX_EXT_LEN);
}

static const struct fmt_magic * search_magic(FILE *ifp) {
	unsigned char magic[sizeof(magic_map->bytes)] = {0};
	const size_t read = fread(magic, 1, MAX_MAG_LEN, ifp);
	fseek(ifp, -(long)read, SEEK_CUR);
	fflush(ifp); /* Ensure the seek propragates to the underlying file
		descriptor. On my machine, tmpfile() files need this while
		fopen() files don't. */
	if (read >= MIN_MAG_LEN) {
		return bsearch(magic, magic_map, ARRAY_LEN(magic_map),
			sizeof(*magic_map), fmaskmagiccmp);
	}
	return NULL;
}

static const struct fmt_ext * search_extension(const struct wuptr name) {
	const size_t max_check = zumin(name.len, MAX_EXT_LEN + 1 /* dot */);
	const unsigned char *end = name.ptr + name.len;
	const unsigned char *ext = memrchr(end - max_check, '.', max_check);
	if (ext) {
		++ext;
		const size_t len = (size_t)(end - ext);
		if (len >= MIN_EXT_LEN) {
			char l_ext[sizeof(ext_map->ext)] = {0};
			for (size_t i = 0; i < len; ++i) {
				l_ext[i] = (char)tolower(ext[i]);
			}
			return bsearch(l_ext, ext_map, ARRAY_LEN(ext_map),
				sizeof(*ext_map), fextcmp);
		}
	}
	return NULL;
}

static int fmtmap_identify_file(FILE *ifp, const char *filename) {
	/* Some formats must be handled specially (i.e. RAW formats which are
	 * actually TIFF), so we search by extension first.
	 * Formats that should be identified by their magic sequence will
	 * return -1. */
	const struct fmt_ext *ext = search_extension(wuptr_str(filename));
	if (ext && ext->id != -1) {
		return ext->id;
	}

	const struct fmt_magic *magic = search_magic(ifp);
	if (magic) {
		return magic->id;
	}
	return -1;
}

bool fmtmap_known_extension(const struct wuptr filename) {
	return (bool)search_extension(filename);
}

enum wu_error dec_callback_image(struct image_context *image,
const enum image_event event) {
	struct image_file *infile = &image->file;
	const enum image_event ev = infile->events & event;
	enum wu_error status = wu_no_change;
	if (ev || !event) {
		const int id = image->fmt_id;
		status = fn_map[id].callback(infile, &image->conf,
			&image->state, ev);
		if (status == wu_ok) {
			image_file_normalize(infile);
		}
	}
	return status;
}

void dec_free_image(struct image_context *image) {
	if (image->file.dec_state) {
		fn_map[image->fmt_id].callback(&image->file, &image->conf,
			&image->state, 0);
	}
	image_file_free(&image->file);
}

static void stat_metadata(struct wu_tree *tree, const int fd) {
	struct stat sb;
	if (fstat(fd, &sb) != 0) {
		return;
	}

	struct wu_tree *meta = tree_add_branch(tree, "Stats");
	if (!meta) {
		return;
	}

	const struct wu_tree_sap sap[] = {
		{"Size", {wu_leaf_signed, {.d = sb.st_size}}},
		{"Last access", {wu_leaf_time, {.time = sb.st_atim.tv_sec}}},
		{"Last modified", {wu_leaf_time, {.time = sb.st_mtim.tv_sec}}},
		{"Last status change", {wu_leaf_time,
			{.time = sb.st_ctim.tv_sec}}},
	};
	tree_bud_leaves(meta, sap, ARRAY_LEN(sap));
}

enum wu_error dec_decode_image(struct image_context *image) {
	struct image_file *infile = &image->file;
	if (!infile->ifp) {
		errno = 0;
		infile->ifp = fopen(image->name, "rb");
		if (!infile->ifp) {
			if (errno) {
				image_file_error_append(infile, strerror(errno));
			}
			return wu_open_error;
		}
	}

	errno = 0;
	image->fmt_id = fmtmap_identify_file(infile->ifp, image->name);
	if (image->fmt_id == -1) {
		if (errno) {
			image_file_error_append(infile, strerror(errno));
			return wu_open_error;
		}
		return wu_unknown_file_type;
	}

	struct wu_tree *metadata = &infile->metadata;
	if (!tree_sow(metadata, "Metadata")) {
		return wu_alloc_error;
	}
	tree_add_leaf_utf8_limit(metadata, "Format", fn_map[image->fmt_id].name,
		sizeof(fn_map[image->fmt_id].name));
	stat_metadata(metadata, fileno(infile->ifp));

	const enum wu_error result = fn_map[image->fmt_id].dec(infile,
		&image->conf);
	if (result == wu_ok) {
		image_file_normalize(infile);
	}
	return result;
}

enum wu_error dec_iter_image(struct image_context *image,
struct raw_img **cur_img) {
	enum wu_error err;
	struct wu_state *state = &image->state;
	if (!image->file.nr) {
		err = dec_decode_image(image);
		*cur_img = image->file.sub_img;
		return err;
	}

	enum image_event ev = 0;
	const struct raw_img *img = image->file.sub_img + state->idx;
	const int frames = (int)raw_img_frames_nr(img);
	if (state->frame + 1 < frames) {
		ev = ev_frame;
		++state->frame;
	} else if (state->idx + 1 < (int)image->file.nr) {
		ev = ev_subcycle;
		++state->idx;
		state->frame = 0;
	}

	if (ev) {
		err = dec_callback_image(image, ev);
		if (err == wu_ok || err == wu_no_change) {
			*cur_img = image->file.sub_img + state->idx;
			err = wu_ok;
		}
		return err;
	}
	return wu_no_change;
}

static void write_max(const void *ptr, const size_t max) {
	fwrite(ptr, 1, strnlen(ptr, max), stdout);
}

static void put_sep(const size_t i, const size_t limit) {
	fputs((i + 1 < limit) ? ", " : "\n\n", stdout);
}

void print_known_formats(void) {
	printf("Known formats: %zu\n", ARRAY_LEN(fn_map));
	for (size_t i = 0; i < ARRAY_LEN(fn_map); ++i) {
		write_max(fn_map[i].name, sizeof(fn_map[i].name));
		put_sep(i, ARRAY_LEN(fn_map));
	}

	printf("Known extensions: %zu\n", ARRAY_LEN(ext_map));
	for (size_t i = 0; i < ARRAY_LEN(ext_map); ++i) {
		write_max(ext_map[i].ext, sizeof(ext_map[i].ext));
		put_sep(i, ARRAY_LEN(ext_map));
	}

	printf("Known magic sequences: %zu\n", ARRAY_LEN(magic_map));
	/*for (size_t i = 0; i < ARRAY_LEN(magic_map); ++i) {
		printf(" %zu:", i);
		for (size_t c = 0; c < sizeof(magic_map[i].bytes); ++c) {
			printf(" %.2x", magic_map[i].bytes[c]);
		}
		putchar('\n');
	}*/
}
