// SPDX-License-Identifier: 0BSD

/*

This file is included by dec_maps.c, generated by dec_comptime -m

*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>

#include <sys/stat.h>

#include "dec.h"
#include "misc/common.h"
#include "misc/math.h"
#include "misc/mem.h"

static int fmaskmagiccmp(const void *restrict m1, const void *restrict m2) {
	const unsigned char *restrict magic1 = m1;
	const struct fmt_magic *restrict magic2 = m2;
	int diff = 0;
	for (size_t i = 0; i < MAX_MAG_LEN; ++i) {
		const unsigned char m = magic2->and_mask[i];
		diff = (magic1[i] & m) - (magic2->bytes[i] & m);
		if (diff) {
			break;
		}
	}
	return diff;
}

static int fextcmp(const void *restrict e1, const void *restrict e2) {
	const char *restrict ext1 = e1;
	const struct fmt_ext *restrict ext2 = e2;
	return memcmp(ext1, ext2->ext, MAX_EXT_LEN);
}

static const struct fmt_magic * search_magic(struct image_file *infile) {
	unsigned char magic[sizeof(magic_map->bytes)] = {0};
	size_t read = 0;
	if (infile->map.data) {
		read = zumin(infile->map.len, MAX_MAG_LEN);
		memcpy(magic, infile->map.data, read);
	} else if (infile->ifp) {
		read = fread(magic, 1, MAX_MAG_LEN, infile->ifp);
	}

	if (read < MIN_MAG_LEN) {
		return NULL;
	}
	return bsearch(magic, magic_map, ARRAY_LEN(magic_map),
		sizeof(*magic_map), fmaskmagiccmp);
}

static const struct fmt_ext * search_extension(const struct wuptr name) {
	const size_t max_check = zumin(name.len, MAX_EXT_LEN + 1 /* dot */);
	if (!max_check) {
		return NULL;
	}
	const uint8_t *end = name.ptr + name.len;
	const uint8_t *dot = memrchr(end - max_check, '.', max_check - 1);
	if (dot) {
		const uint8_t *ext = dot + 1;
		const size_t len = (size_t)(end - ext);
		if (len >= MIN_EXT_LEN) {
			uint8_t l_ext[sizeof(ext_map->ext)] = {0};
			for (size_t i = 0; i < len; ++i) {
				l_ext[i] = (uint8_t)tolower(ext[i]);
			}
			return bsearch(l_ext, ext_map, ARRAY_LEN(ext_map),
				sizeof(*ext_map), fextcmp);
		}
	}
	return NULL;
}

static const struct fmt_desc * fmtmap_identify(struct image_context *image) {
	/* Some formats must be handled specially (i.e. RAW formats which are
	 * actually TIFF), so we search by extension first.
	 * Formats that should be identified by their magic sequence will
	 * return -1. */
	if (image->name) {
		const struct fmt_ext *ext = search_extension(wuptr_str(image->name));
		if (ext && ext->id >= 0) {
			return desc_map + ext->id;
		}
	}

	const struct fmt_magic *magic = search_magic(&image->file);
	if (magic) {
		return desc_map + magic->id;
	}
	return NULL;
}


bool fmtmap_known_extension(const struct wuptr filename) {
	return (bool)search_extension(filename);
}


void dec_free_image(struct image_context *image) {
	if (image->file.dec_state) {
		image->fn->callback(&image->file, &image->conf, &image->state, 0);
	}
	image_file_free(&image->file);
}

enum wu_error dec_callback(struct image_context *image,
enum image_event event) {
	struct image_file *infile = &image->file;
	struct wu_state *state = &image->state;
	if (event != ev_end) {
		event &= infile->events;
		switch (event) {
		case ev_end:
			return wu_no_change;
		case ev_subcycle:
			if (infile->sub_img[state->idx].data) {
				return wu_no_change;
			}
			break;
		default:
			break;
		}
	}
	const enum wu_error status = image->fn->callback(infile, &image->conf,
		state, event);
	if (status == wu_ok) {
		image_file_normalize(infile);
	}
	return status;
}

static enum wu_error init_metadata(struct image_file *infile,
const struct fmt_desc *fmt, const int fd) {
	struct wu_tree *metadata = &infile->metadata;
	if (!tree_sow(metadata, "Metadata")) {
		return wu_alloc_error;
	}

	if (fmt) {
		tree_add_leaf_utf8_limit(metadata, "Format",
			WUPTR_ARRAY(fmt->name));
	}

	struct stat sb;
	if (fstat(fd, &sb) != 0) {
		return wu_ok;
	}

	struct wu_tree *fdmeta = tree_add_branch(metadata, "Stats");
	if (!fdmeta) {
		return wu_alloc_error;
	}

	const struct wu_tree_sap sap[] = {
		{"Size", {wu_leaf_signed, {.d = sb.st_size}}},
		{"Last access", {wu_leaf_time, {.time = sb.st_atim.tv_sec}}},
		{"Last modified", {wu_leaf_time, {.time = sb.st_mtim.tv_sec}}},
		{"Last status change", {wu_leaf_time,
			{.time = sb.st_ctim.tv_sec}}},
	};
	tree_bud_leaves(fdmeta, sap, ARRAY_LEN(sap));
	return wu_ok;
}

static void errno_append(struct image_file *infile, const int n) {
	if (n) {
		image_file_strerror_append(infile, strerror(n));
	}
}

static enum wu_error actually_open(struct image_context *image) {
	struct image_file *infile = &image->file;
	struct map_info *map = &infile->map;
	if (!infile->ifp && !map->data) {
		if (!image->name) {
			fatal_bug("dec_decode()",
				"No data source for image_context");
		}
		errno = 0;
		infile->ifp = fopen(image->name, "rb");
		if (!infile->ifp) {
			errno_append(infile, errno);
			return wu_open_error;
		}
	}

	const struct fmt_desc *fmt = NULL;
	if (!image->fn) {
		errno = 0;
		fmt = fmtmap_identify(image);
		if (!fmt) {
			errno_append(infile, errno);
			return wu_unexpected_eof;
		}
		image->fn = fmt->fn;
	}

	int fd = -1;
	if (infile->ifp) {
		fd = fileno(infile->ifp);
		if (image->fn->mmap) {
			if (!map->data) {
				errno = 0;
				if (!file_map_fd(map, fd)) {
					errno_append(infile, errno);
					return wu_open_error;
				}
			}
		} else {
			rewind(infile->ifp);
			fflush(infile->ifp); /* tmpfiles require this */
		}
	} else {
		if (!image->fn->mmap) {
			errno = 0;
			infile->ifp = fmemopen((uint8_t *)map->data, map->len,
				"rb");
			if (!infile->ifp) {
				errno_append(infile, errno);
				return wu_alloc_error; // ???
			}
		}
	}
	return init_metadata(infile, fmt, fd);
}

enum wu_error dec_decode(struct image_context *image) {
	enum wu_error st = actually_open(image);
	if (st == wu_ok) {
		struct image_file *infile = &image->file;
		const struct wu_conf *conf = &image->conf;
		st = image->fn->dec(infile, conf);
		if (st == wu_ok) {
			image_file_normalize(infile);
			if (infile->events & ev_subcycle) {
				st = dec_callback(image, ev_subcycle);
				if (st == wu_no_change) {
					st = wu_ok;
				}
			}
		}
	}
	return st;
}

enum wu_error dec_iter(struct image_context *image,
struct wuimg **cur_img) {
	enum wu_error err;
	struct wu_state *state = &image->state;
	if (!image->file.nr) {
		err = dec_decode(image);
		*cur_img = image->file.sub_img;
		return err;
	}

	enum image_event ev = 0;
	const struct wuimg *img = image->file.sub_img + state->idx;
	const int frames = (int)wuimg_frames_nr(img);
	if (state->frame + 1 < frames) {
		ev = ev_frame;
		++state->frame;
	} else if (state->idx + 1 < (int)image->file.nr) {
		ev = ev_subcycle;
		++state->idx;
		state->frame = 0;
	}

	if (ev) {
		err = dec_callback(image, ev);
		if (err == wu_ok || err == wu_no_change) {
			*cur_img = image->file.sub_img + state->idx;
			err = wu_ok;
		}
		return err;
	}
	return wu_no_change;
}

void dec_src_mem(struct image_context *image, const struct wuptr data,
const char *name, const struct image_fn *fn) {
	image->name = name;
	image->file.map = (struct map_info) {
		.data = data.ptr,
		.len = data.len,
	};
	image->file.keep_map = true;
	image->fn = fn;
}

void dec_src_file(struct image_context *image, FILE *ifp, const char *name,
const bool keep_file) {
	image->name = name;
	image->file.ifp = ifp;
	image->file.keep_file = keep_file;
}

void dec_src_filename(struct image_context *image, const char *filename) {
	image->name = filename;
}


static void write_max(const void *ptr, const size_t max) {
	fwrite(ptr, 1, strnlen(ptr, max), stdout);
}

static void put_sep(const size_t i, const size_t limit) {
	fputs((i + 1 < limit) ? ", " : "\n\n", stdout);
}

void print_known_formats(void) {
	printf("Known formats: %zu\n", ARRAY_LEN(desc_map));
	for (size_t i = 0; i < ARRAY_LEN(desc_map); ++i) {
		write_max(desc_map[i].name, sizeof(desc_map[i].name));
		put_sep(i, ARRAY_LEN(desc_map));
	}

	printf("Known extensions: %zu\n", ARRAY_LEN(ext_map));
	for (size_t i = 0; i < ARRAY_LEN(ext_map); ++i) {
		write_max(ext_map[i].ext, sizeof(ext_map[i].ext));
		put_sep(i, ARRAY_LEN(ext_map));
	}

	printf("Known magic sequences: %zu\n", ARRAY_LEN(magic_map));
	/*for (size_t i = 0; i < ARRAY_LEN(magic_map); ++i) {
		printf(" %zu:", i);
		for (size_t c = 0; c < sizeof(magic_map[i].bytes); ++c) {
			printf(" %.2x", magic_map[i].bytes[c]);
		}
		putchar('\n');
	}*/
}
