// SPDX-License-Identifier: 0BSD
// SPDX-FileCopyrightText: 2024 kaleido
/*

This file is included by dec_maps.c, generated by `comptime.py maps`

*/

#include <ctype.h>
#include <stdio.h>

#include "misc/common.h"
#include "misc/math.h"
#include "misc/mem.h"

static int fmaskmagiccmp(const void *restrict m1, const void *restrict m2) {
	const unsigned char *restrict magic1 = m1;
	const struct fmt_magic *restrict magic2 = m2;
	int diff = 0;
	for (size_t i = 0; !diff && i < MAX_MAG_LEN; ++i) {
		const unsigned char m = magic2->and_mask[i];
		diff = (magic1[i] & m) - (magic2->bytes[i] & m);
	}
	return diff;
}

static int fextcmp(const void *restrict e1, const void *restrict e2) {
	const char *restrict ext1 = e1;
	const struct fmt_ext *restrict ext2 = e2;
	return memcmp(ext1, ext2->ext, MAX_EXT_LEN);
}

static const struct fmt_magic * search_magic(struct image_file *infile) {
	unsigned char magic[sizeof(magic_map->bytes)] = {0};
	size_t read = 0;
	if (infile->map.ptr) {
		read = zumin(infile->map.len, MAX_MAG_LEN);
		memcpy(magic, infile->map.ptr, read);
	} else if (infile->ifp) {
		read = fread(magic, 1, MAX_MAG_LEN, infile->ifp);
	}

	if (read < MIN_MAG_LEN) {
		return NULL;
	}
	for (size_t i = 0; i < ARRAY_LEN(magic_map); ++i) {
		if (!fmaskmagiccmp(magic, magic_map + i)) {
			return magic_map + i;
		}
	}
	return NULL;
}

static const struct fmt_ext * search_extension(const struct wuptr name,
uint8_t l_ext[static sizeof(ext_map->ext)]) {
	const size_t max_check = zumin(name.len, MAX_EXT_LEN + 1 /* dot */);
	if (!max_check) {
		return NULL;
	}
	const uint8_t *end = name.ptr + name.len;
	const uint8_t *dot = memrchr(end - max_check, '.', max_check - 1);
	if (dot) {
		const uint8_t *ext = dot + 1;
		const size_t len = (size_t)(end - ext);
		if (len >= MIN_EXT_LEN) {
			for (size_t i = 0; i < len; ++i) {
				l_ext[i] = (uint8_t)tolower(ext[i]);
			}
			return bsearch(l_ext, ext_map, ARRAY_LEN(ext_map),
				sizeof(*ext_map), fextcmp);
		}
	}
	return NULL;
}

const struct fmt_desc * fmtmap_identify(struct image_context *image) {
	/* Some formats must be handled specially (i.e. RAW formats which are
	 * actually TIFF), so we search by extension first.
	 * Formats that should be identified by their magic sequence will
	 * return -1. */
	if (image->name) {
		const struct fmt_ext *ext = search_extension(wuptr_str(image->name),
			image->file.ext);
		if (ext && ext->id >= 0) {
			return desc_map + ext->id;
		}
	}

	const struct fmt_magic *magic = search_magic(&image->file);
	if (magic) {
		return desc_map + magic->id;
	}
	return NULL;
}

static int namecmp(const void *n, const void *d) {
	const char *name = n;
	const struct fmt_desc *desc = d;
	return strncmp(name, desc->name, sizeof(desc->name));
}

const struct fmt_desc * fmtmap_by_name(const char *name) {
	return bsearch(name, desc_map, ARRAY_LEN(desc_map), sizeof(*desc_map),
		namecmp);
}

bool fmtmap_known_extension(const struct wuptr filename) {
	uint8_t buf[sizeof(ext_map->ext)] = {0};
	return (bool)search_extension(filename, buf);
}

static void print_descs(FILE *out) {
	int max = (int)sizeof(desc_map->name);
	for (size_t i = 0; i < ARRAY_LEN(desc_map); ++i) {
		fprintf(out, "%.*s:\t%s\n", max, desc_map[i].name,
			desc_map[i].description);
	}
	fputc('\n', out);
}

void fmtmap_print_known(FILE *ofp) {
	fprintf(ofp, "Known formats: %zu\n", ARRAY_LEN(desc_map));
	print_descs(ofp);

	fprintf(ofp, "Known extensions: %zu\n", ARRAY_LEN(ext_map));
	const int max = (int)sizeof(ext_map->ext);
	for (size_t i = 0; i < ARRAY_LEN(ext_map); ++i) {
		fprintf(ofp, "%.*s%s", max, ext_map[i].ext,
			(i + 1 < ARRAY_LEN(ext_map)) ? ", " : "\n\n");
	}

	fprintf(ofp, "Known magic sequences: %zu\n", ARRAY_LEN(magic_map));
}
