// SPDX-License-Identifier: 0BSD
// SPDX-FileCopyrightText: 2024 kaleido
/*

This file is included by dec_maps.c, generated by `comptime.py maps`

*/

#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "misc/common.h"
#include "misc/math.h"
#include "misc/mem.h"

struct confidence {
	int fmt;
	int bits;
};

struct detect {
	struct confidence con[6];
	size_t found;
};

static int fmaskmagiccmp(const void *restrict m1, const void *restrict m2) {
	const unsigned char *restrict magic1 = m1;
	const struct fmt_magic *restrict magic2 = m2;
	int diff = 0;
	for (size_t i = 0; !diff && i < MAX_MAG_LEN; ++i) {
		const unsigned char m = magic2->and_mask[i];
		diff = (magic1[i] & m) - magic2->bytes[i];
	}
	return diff;
}

static int fextcmp(const void *restrict e1, const void *restrict e2) {
	const char *restrict ext1 = e1;
	const struct fmt_ext *restrict ext2 = e2;
	return memcmp(ext1, ext2->ext, MAX_EXT_LEN);
}

static int bitcount(unsigned char c) {
	int b = 0;
	while (c) {
		b += c & 1;
		c >>= 1;
	}
	return b;
}

static int magic_bits(const struct fmt_magic *m) {
	int bits = 0;
	for (size_t i = 0; i < ARRAY_LEN(m->bytes); ++i) {
		bits += bitcount(m->bytes[i]);
	}
	return bits;
}

static bool new_fmt(struct detect *det, const int fmt) {
	for (size_t i = 0; i < det->found; ++i) {
		if (det->con[i].fmt == fmt) {
			return false;
		}
	}
	return true;
}

static void search_magic(struct image_file *infile, struct detect *det) {
	unsigned char magic[sizeof(magic_map->bytes)] = {0};
	size_t read = 0;
	if (infile->map.ptr) {
		read = zumin(infile->map.len, MAX_MAG_LEN);
		memcpy(magic, infile->map.ptr, read);
	} else if (infile->ifp) {
		read = fread(magic, 1, MAX_MAG_LEN, infile->ifp);
	}

	if (read >= MIN_MAG_LEN) {
		for (size_t i = 0; i < ARRAY_LEN(magic_map); ++i) {
			if (!fmaskmagiccmp(magic, magic_map + i)
			&& new_fmt(det, magic_map[i].id)) {
				det->con[det->found] = (struct confidence) {
					.fmt = magic_map[i].id,
					.bits = magic_bits(magic_map + i),
				};
				++det->found;
				if (det->found == ARRAY_LEN(det->con)) {
					break;
				}
			}
		}
	}
}

static const struct fmt_ext * search_extension(const struct wuptr name,
uint8_t l_ext[static sizeof(ext_map->ext)]) {
	const size_t max_check = zumin(name.len, MAX_EXT_LEN + 1 /* dot */);
	if (!max_check) {
		return NULL;
	}
	const uint8_t *end = name.ptr + name.len;
	const uint8_t *dot = memrchr(end - max_check, '.', max_check - 1);
	if (dot) {
		const uint8_t *ext = dot + 1;
		const size_t len = (size_t)(end - ext);
		if (len >= MIN_EXT_LEN) {
			for (size_t i = 0; i < len; ++i) {
				l_ext[i] = (uint8_t)tolower(ext[i]);
			}
			return bsearch(l_ext, ext_map, ARRAY_LEN(ext_map),
				sizeof(*ext_map), fextcmp);
		}
	}
	return NULL;
}

static void add_confidence(struct detect *det, const int fmt, const int bits) {
	size_t where = ARRAY_LEN(det->con);
	int min_bits = bits;
	for (size_t i = 0; i < det->found; ++i) {
		if (det->con[i].fmt == fmt) {
			det->con[i].bits += bits;
			return;
		} else if (det->con[i].bits < min_bits) {
			where = i;
			min_bits = det->con[i].bits;
		}
	}
	if (det->found < ARRAY_LEN(det->con)) {
		where = det->found;
		++det->found;
	}
	if (where < ARRAY_LEN(det->con)) {
		det->con[where] = (struct confidence){.fmt = fmt, .bits = bits};
		det->found += det->found == where;
	}
}

static void search_size(struct image_file *infile, struct detect *det) {
	/* Sizes are in descending order */
	const size_t size = image_file_size(infile);
	const int size_bits = 2;
	for (size_t i = 0; i < ARRAY_LEN(size_map); ++i) {
		if (size > size_map[i].size) {
			break;
		} else if (size == size_map[i].size) {
			add_confidence(det, size_map[i].id, size_bits);
		}
	}
}

static int consort(const void *v1, const void *v2) {
	const struct confidence *c1 = v1;
	const struct confidence *c2 = v2;
	/* Sort confidence bits from most to least, then formats from
	 * higher to lower ID, itself assigned in alphabetical order.
	 * That's only to ensure TIFF comes before RAW when the extension
	 * doesn't add any information. */
	return (c2->bits - c1->bits) * 4096 + (c2->fmt - c1->fmt);
}

const struct fmt_desc * fmtmap_identify(struct image_file *file,
const char *name) {
	struct detect det;
	det.con[0].bits = 0;
	det.found = 0;

	search_magic(file, &det);
	search_size(file, &det);
	if (name) {
		const int ext_bits = 4;
		const struct fmt_ext *ext = search_extension(
			wuptr_str(name), file->ext);
		if (ext && ext->id > fmt_unknown) {
			add_confidence(&det, ext->id, ext_bits);
		}
	}

	qsort(det.con, det.found, sizeof(*det.con), consort);
	if (getenv("WU_DEBUG")) {
		fputs("Detection confidence:\n", stderr);
		for (size_t i = 0; i < det.found && det.con[i].fmt > fmt_unknown; ++i) {
			fprintf(stderr, " %.8s: %d\n",
				desc_map[det.con[i].fmt].name, det.con[i].bits);
		}
	}
	const int min_bits = 2;
	if (det.con[0].bits >= min_bits) {
		return desc_map + det.con[0].fmt;
	}
	return NULL;
}

static int namecmp(const void *n, const void *d) {
	const char *name = n;
	const struct fmt_desc *desc = d;
	return strncmp(name, desc->name, sizeof(desc->name));
}

const struct fmt_desc * fmtmap_by_name(const char *name) {
	return bsearch(name, desc_map, ARRAY_LEN(desc_map), sizeof(*desc_map),
		namecmp);
}

bool fmtmap_known_extension(const struct wuptr filename) {
	uint8_t buf[sizeof(ext_map->ext)] = {0};
	return (bool)search_extension(filename, buf);
}

static void print_descs(FILE *out) {
	int max = (int)sizeof(desc_map->name);
	for (size_t i = 0; i < ARRAY_LEN(desc_map); ++i) {
		fprintf(out, "%.*s:\t%s\n", max, desc_map[i].name,
			desc_map[i].description);
	}
	fputc('\n', out);
}

void fmtmap_print_known(FILE *ofp) {
	fprintf(ofp, "Known formats: %zu\n", ARRAY_LEN(desc_map));
	print_descs(ofp);

	fprintf(ofp, "Known extensions: %zu\n", ARRAY_LEN(ext_map));
	const int max = (int)sizeof(ext_map->ext);
	for (size_t i = 0; i < ARRAY_LEN(ext_map); ++i) {
		fprintf(ofp, "%.*s%s", max, ext_map[i].ext,
			(i + 1 < ARRAY_LEN(ext_map)) ? ", " : "\n\n");
	}

	fprintf(ofp, "Known magic sequences: %zu\n", ARRAY_LEN(magic_map));
}
